apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ng-app
  template:
    metadata:
      labels:
        app: ng-app
    spec:
      containers:
      - name: ng-app
        image: schaugule/playwrightui:v2.0
        resources:
          limits:
            memory: "256Mi"
            cpu: "750m"
        ports:
        - containerPort: 4300
      
---

apiVersion: v1
kind: Service
metadata:
  name: ng-app
spec:
  selector:
    app: ng-app
  ports:
  - port: 4302
    targetPort: 4300
  type: LoadBalancer